name: FloateingSights4var2
options:
  bundleIdPrefix: takashiki
  deploymentTarget:
    iOS: "11.0"
  xcodeVersion: "0900"

targets:
  FloateingSights4var2:
    type: application
    platform: iOS
    sources:
      - FloateingSights4var2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: takashiki.FloateingSights4var2
        PRODUCT_NAME: FloateingSights4var2
        SWIFT_VERSION: "5"
        TARGETED_DEVICE_FAMILY: "2"
        INFOPLIST_FILE: FloateingSights4var2/Info.plist
        DEVELOPMENT_TEAM: GY636G2259
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    scheme:
      gatherCoverageData: false
